# Project-wide Gradle settings.
android.useAndroidX=true
android.suppressUnsupportedCompileSdk=36

# Increase JVM Heap memory for D8 dexing and compilation to prevent OutOfMemoryError
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+UseG1GC
org.gradle.parallel=true
org.gradle.caching=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
